### ISSUE TITLE
Message over 2000 characters error occuring on exception log.

### ISSUE THREAD

**Issue by Fires1** [USRDiscordBots/Sandwich-Delivery-Bot-v2.0#11]
https://github.com/USRDiscordBots/Sandwich-Delivery-Bot-2.0/blob/master/SandwichDeliveryBot3/Modules/Public/SandwichModule.cs#L348

This line is causing error _i think_ because when it finds an exception the exception is larger then 2000 characters.

I suggest having it WriteLine the error, then it can be searched for inside the actual bot. We need a working example of it first.

**Comment by Fires1** [comment]
![](http://i.imgur.com/45wVnGR.png)

Included image.

**Comment by Fires1** [comment]
(triple post sorry)

If someone manages to recreate this issue we need to get in contact with the customer and try to go from there. I have no idea how something like this happens.

I think a possible change could be switching form our data saving system and try to get the server from the client every time an order/order info is requested. This will slow down response times but I feel it _could_ be helpful in removal of orders. Another idea is that if an error occurs we need to delete the order.

Will make a second issue on any errors occurring with commands that remove orders.

**Comment by LemonIsANicePerson** [comment]
If the bot cannot create an instant invite link it will say: **Error:** Message content is too long, length must be less or equal to 2000. Parameter name: Content.

if you didn't know already I think the error was too long so it never sent it

**Comment by Fires1** [comment]
Thank you @LemonIsANicePerson.
I believe at this point what is going on is that 

You go to deliver
>Invite attempted to be created
>Invite obviously not being create
>Throwing an error
>Error should be logged
>Error attempts to be logged but instead throws another Discord error due to being too long.

Thank you so very much, I think we can probably fix this very soon.
